name = "nomen"
main = "worker/index.ts"
compatibility_date = "2024-04-01"
assets = { directory = "dist", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "nomen-db"
database_id = "7bef5d93-07be-4c99-b70c-b07acff8f2e5"
migrations_dir = "drizzle"
